sudo: required

language: go

go:
 - 1.8.x

env:
 - DOCKER_COMPOSE_VERSION=1.14.0

services:
 - docker

cache:
 directories:
  - vendor

before_install:
 - make run.kafka
 - curl https://glide.sh/get | sh

install: make install

script: 
 - make test
 - go build
